### ISSUE TITLE
when I import torch_points_kernels.points_cuda , there is a problem.

### ISSUE THREAD

**Issue by DJY1995-djy** [nicolas-chaulet/torch-points-kernels#31]
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'

**Comment by nicolas-chaulet** [comment]
Hi, could you please be a bit more specific? Which version of torch_points_kernels are you using?
In principle you should not have to import points_cpu and you should only use the high level methods available in  torch_points_kernels directly.

**Comment by DJY1995-djy** [comment]
The version of torch_points_kernels is 0.6.1, which I installed&nbsp; with pip. I notice that the error is there are no module named points_cpu and pointds_cuda.I'am so confused. And， how to&nbsp;use the high level methods available in torch_points_kernels directly.&nbsp;Thank you for your reply！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicolas Chaulet"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上9:05
收件人: "nicolas-chaulet/torch-points-kernels"<torch-points-kernels@noreply.github.com&gt;; 
抄送: "不想放手"<344091566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nicolas-chaulet/torch-points-kernels] when I import torch_points_kernels.points_cuda , there is a problem. (#31)





 
Hi, could you please be a bit more specific? Which version of torch_points_kernels are you using?
 In principle you should not have to import points_cpu and you should only use the high level methods available in  torch_points_kernels directly.

**Comment by nicolas-chaulet** [comment]
Hi, 
You can take a look at the tests for examples but in general, simply do:
```
from torch_points_kernels import knn
import torch

support = torch.tensor([[[0, 0, 0], [1, 0, 0], [2, 0, 0]]]).float()
query = torch.tensor([[[0, 0, 0]]]).float()
idx, dist = knn(support, query, 3)
```

**Comment by DJY1995-djy** [comment]
But, import doesn't work.
Just like this.
&gt;&gt;&gt; from torch_points_kernels import knn&nbsp;&nbsp;
Traceback (most recent call last):
&nbsp; File "<stdin&gt;", line 1, in <module&gt;
&nbsp; File "D:\Anaconda\lib\site-packages\torch_points_kernels\__init__.py", line 1, in <module&gt;
&nbsp; &nbsp; from .torchpoints import *
&nbsp; File "D:\Anaconda\lib\site-packages\torch_points_kernels\torchpoints.py", line 7, in <module&gt;
&nbsp; &nbsp; import torch_points_kernels.points_cpu as tpcpu
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicolas Chaulet"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上10:21
收件人: "nicolas-chaulet/torch-points-kernels"<torch-points-kernels@noreply.github.com&gt;; 
抄送: "不想放手"<344091566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nicolas-chaulet/torch-points-kernels] when I import torch_points_kernels.points_cuda , there is a problem. (#31)





 
Hi,
 You can take a look at the tests for examples but in general, simply do:
 from torch_points_kernels import knn import torch support = torch.tensor([[[0, 0, 0], [1, 0, 0], [2, 0, 0]]]).float() query = torch.tensor([[[0, 0, 0]]]).float() idx, dist = knn(support, query, 3)

**Comment by nicolas-chaulet** [comment]
Alright, looks like you're running on windows correct? If that's the case it might very well be that the libraries never compiled, we have never tried compiling those on windows. Otherwise it is certainly a problem with the installation, it seems that it does not compile the c++ code. Are you sure it installs properly? I.e no error? Last thing, did you install pytorch before installing it? You must have pytorch installed before running the pip install.

**Comment by DJY1995-djy** [comment]
Yes, I have installed pytorch before, the same problem I will encounter when I tested it on Ubuntu. I simply used the command pip to install it.Actually, I never complied the c++ code. There are just few python files in the lib filepath.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nicolas Chaulet"<notifications@github.com&gt;; 
发送时间: 2020年5月14日(星期四) 晚上10:49
收件人: "nicolas-chaulet/torch-points-kernels"<torch-points-kernels@noreply.github.com&gt;; 
抄送: "不想放手"<344091566@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nicolas-chaulet/torch-points-kernels] when I import torch_points_kernels.points_cuda , there is a problem. (#31)





 
Alright, looks like you're running on windows correct? If that's the case it might very well be that the libraries never compiled, we have never tried compiling those on windows. Otherwise it is certainly a problem with the installation, it seems that it does not compile the c++ code. Are you sure it installs properly? I.e no error? Last thing, did you install pytorch before installing it? You must have pytorch installed before running the pip install.

**Comment by nicolas-chaulet** [comment]
So that's the thing. Just install pytorch first and it should work! I have added a word about that on the README. We can't really fix the issue as far as I can tell, it's python dependency management problem... Let us know if you still have this issue.
