### ISSUE TITLE
Difference between dense knn and knn

### ISSUE THREAD

**Issue by zhangmozhe** [nicolas-chaulet/torch-points-kernels#38]
Hi @nicolas-chaulet, I really like this library which is useful for point cloud. I wonder the difference between dense knn and knn.  Also, what does it mean by dense ball query? 

Also, a brief document with sample code will be useful.

**Comment by nicolas-chaulet** [comment]
Hi, thanks! 
The knn algorithm here is for "dense" or packed data layouts as opposed to sparse data layouts. More about that here:
https://torch-points3d.readthedocs.io/en/latest/src/advanced.html#data-formats-for-point-cloud

Regarding the dense ball query, again it is about the format of the data. The API exposes a single method `ball_query` which is the one you should use. Hopefully the method's docstring is clear enough... Regarding examples, take a look at the tests, they should be a good starting point!
