### ISSUE TITLE
pip installation doesn't include cuda version

### ISSUE THREAD

**Issue by pvnieo** [nicolas-chaulet/torch-points-kernels#39]
Hi,

I installed torch-points-kernels unsing the pip command:
```pip install torch-points-kernels```, but suprinsingly, it doesn't install the cuda version. In fact ```import torch_points_kernels.points_cuda``` produce an `ModuleNotFoundError`.

I had to clone the git repo, and build the code on my machine.
Is this a problem related to the installed version of torch, cuda, etc?

**Comment by nicolas-chaulet** [comment]
Hi,
This is probably because it cannot find CUDA. What does the following python code give you?
```
from torch.utils.cpp_extension import  CUDA_HOME
print(CUDA_HOME)
```
It should return the path to your CUDA installation.

**Comment by pvnieo** [comment]
Hi,
It gives the following: `/usr`.

**Comment by nicolas-chaulet** [comment]
Ok, something is wrong then. Could you add you cuda bin directory to the PATH environment variable? It should be something like 
```
export PATH="/usr/local/cuda-10.2/bin:$PATH"
```
and run the command again?

**Comment by pvnieo** [comment]
Hi,
It gives the same output even after adding the cuda bin to the PATH env.

**Comment by zeqinLi** [comment]
Hi,I have the same problem.When i run the code:

> ```
> from torch.utils.cpp_extension import  CUDA_HOME
> print(CUDA_HOME)

The code return the result:
> public/software/cuda/10.1

But  when i import torch_points_kernels.points_cuda,the following error occurred:
> ModuleNotFoundError: No module named 'torch_points_kernels.points_cuda'

In the path(/public/software/anaconda3-5.2.0/envs/pytorch/lib/python3.6/site-packages/torch_points _kernel) there are only the following files：
![image](https://user-images.githubusercontent.com/46022740/84467484-ed13b480-acae-11ea-8e69-4e67b3ad6f96.png)

The system I use is ubuntu. How can i solve this problem?

**Comment by nicolas-chaulet** [comment]
@pvnieo Are you using conda to create the virtual env and to install torch-points-kernels? If yes then that is probably the issue. I haven't managed to fix conda installs. I would recommend using plain virtual envs until this is fixed (contributions welcome, I am not very familiar with conda!)
```
python -m venv tp3denv
source tp3denv/bin/activate
pip install torch
pip install torch-points-kernels
```
This should work just fine.

**Comment by nicolas-chaulet** [comment]
#37

**Comment by pvnieo** [comment]
@nicolas-chaulet No I'm not using conda or virtual env, I installed the library using pip.
Also, I tried to find the bin for cuda but I didn't find it. The path you provided is empty.

**Comment by nicolas-chaulet** [comment]
What does `nvidia-smi` give you? And
```
import torch
print(torch.cuda.is_available())
```
It looks like it cannot find cuda properly...

**Comment by pvnieo** [comment]
`torch.cuda.is_available()` gives `True`.
nvidia-smi gives the details about my gpu and  CUDA version:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   58C    P5     8W /  N/A |    836MiB /  6078MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+

```

**Comment by nicolas-chaulet** [comment]
Alright, that's weird. Could you post the logs of 
```
pip uninstall torch-points-kernels
pip install torch-points-kernels --no-cache
```
please? Just trying to udnerstand what's going on...

**Comment by nicolas-chaulet** [comment]
I have added some troubleshooting steps in teh README, would you mind trying and letting me know if that helps?|
https://github.com/nicolas-chaulet/torch-points-kernels#troubleshooting

**Comment by pvnieo** [comment]
Hi, I have reinstalled  torch kernel points in an another server, but this time I didn't got the error message. I'll let you know if I can reproduce it!

**Comment by pvnieo** [comment]
Hi @nicolas-chaulet ,
I got the same issue again, here's the output of:
```
from torch.utils.cpp_extension import  CUDA_HOME
print(CUDA_HOME)
```
```
/usr/local/cuda
```

**Comment by nicolas-chaulet** [comment]
I am pretty certain it is related to PATH variable, could you run through the trouble shooting steps here?
https://github.com/nicolas-chaulet/torch-points3d#cannot-compile-certain-cuda-kernels-or-seg-faults-while-running-the-tests

**Comment by yuminhhuang** [comment]
I solve my problem because the setup.py will check whether there is GPU in env. So I need to allocate GPU first in cluster and then build this project use setup.py. Then in my case the build result will not auto generate to lib/python3.9/site-packages/torch_points_kernels/, so I copy torch_points_kernels/ directory to there maully. Finally both points_cpu.so and points_cuda.so prepared and I works.
