### ISSUE TITLE
CPU only install

### ISSUE THREAD

**Issue by DLwbm123** [nicolas-chaulet/torch-points-kernels#41]
Because I only use knn.py and which seems performed in cpu. :)

**Comment by nicolas-chaulet** [comment]
There is no way to force CPU only at the moment. If you have a GPU it will compile the CUDA kernels. Is this a problem?

**Comment by DLwbm123** [comment]
Yes, I tried to install with torch==1.1.0 and CUDA 9.0 and failed with the same error("TORCH_CHECK") in  #37 . The installation is successful on my laptop without GPU. So I wonder if torch-points-kernels can be installed with CPU only.

**Comment by nicolas-chaulet** [comment]
Not at the moment no... You could clone the repo and deactivate CUDA install manually before installing from source.

**Comment by vlaminckaxel** [comment]
https://github.com/nicolas-chaulet/torch-points-kernels/pull/60

**Comment by nicolas-chaulet** [comment]
Do you think that would work when installing the package in a docker image (for example during CI)?

**Comment by vlaminckaxel** [comment]
If we have a docker with Cuda installed it should be possible. 
But to test not only the compilation of the ops we also should have a GPU instance.

I will upgrade the cicd pipeline.

**Comment by nicolas-chaulet** [comment]
@CCInc This was solved right?

**Comment by vlaminckaxel** [comment]
Can we tag a new release with these improvements?

**Comment by nicolas-chaulet** [comment]
Yes doing that now!

**Comment by nicolas-chaulet** [comment]
Ok, 0.7.0 should be published now! Let me know if that works for you and we can close this issue.

**Comment by Stakhan** [comment]
Hi there,

I was also trying to install torch-points-kernels (to further install torch-points3d) with CPU only version and I can confirm it works on my side (Ubuntu 20.04) with version 0.7.0.

**Comment by nicolas-chaulet** [comment]
Thanks!
