### ISSUE TITLE
Prebuilt Wheels

### ISSUE THREAD

**Issue by CCInc** [nicolas-chaulet/torch-points-kernels#53]
Torch geometric provides pre-built wheels for the `torch-scatter`, `torch-sparse` and all others that need to be built, would it be possible to get a wheel for this library?

**Comment by nicolas-chaulet** [comment]
Hi Chris! In principle yes, we would just need to setup the CI pipeline for that using some appropriate docker images to build the binaries.

**Comment by CCInc** [comment]
I'll close this in favor of the conda build 😄
