### ISSUE TITLE
undefined symbol: _ZN5torch3jit6tracer9addInputsEPNS0_4NodeEPKcRKN3c1013TensorOptionsE

### ISSUE THREAD

**Issue by aRI0U** [nicolas-chaulet/torch-points-kernels#54]
Hi,
I just installed `torch-points-kernels` using `pip` and when I try to import the package, I get the following error:
```
>>> import torch_points_kernels
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alain/.local/lib/python3.8/site-packages/torch_points_kernels/__init__.py", line 1, in <module>
    from .torchpoints import *
  File "/home/alain/.local/lib/python3.8/site-packages/torch_points_kernels/torchpoints.py", line 7, in <module>
    import torch_points_kernels.points_cpu as tpcpu
ImportError: /home/alain/.local/lib/python3.8/site-packages/torch_points_kernels/points_cpu.so: undefined symbol: _ZN5torch3jit6tracer9addInputsEPNS0_4NodeEPKcRKN3c1013TensorOptionsE
```
I use:
- Ubuntu 20.04
- Python 3.8.5
- PyTorch 1.7.0
- CPU only (my laptop does not have a GPU)

The error occured in a file called `points_cpu.so` so I suppose it is not related to some CUDA stuff. Have you ever encountered such an error, or do you have any idea what it can be?

Thanks,
Alain

**Comment by nicolas-chaulet** [comment]
This is likely because is has been previously installed with another version of pytorch. Could that be?

**Comment by aRI0U** [comment]
It could, but I uninstalled and reinstalled the package after I upgraded to PyTorch 1.7. Are there any files that I should delete manually before reinstalling?

**Comment by nicolas-chaulet** [comment]
That's fine, it actually uses cached compiled files that were compiled against an older pytorch. So to fix that just run 
```
pip install torch-points-kernels --no-cache
```
(after uninstalling it)

Also, we have never tried it on pytorch 1.7 so that could be an issue as well but it should break at compilation time not at run time.

**Comment by aRI0U** [comment]
You were right, that works now.
Thanks a lot!
