### ISSUE TITLE
ModuleNotFoundError: No module named 'torch_points_kernels.points_cpu'

### ISSUE THREAD

**Issue by marsDurden** [nicolas-chaulet/torch-points-kernels#64]
Hi, in installed torch_points_kernels via pip but I got this error while executing `from torch_points_kernels import knn`

In the torch_points_kernels directory in my venv I can't find the `setup.py` file to compile the project.
Is there something I'm missing?

Btw I'm using python 3.9 and PyCharm as IDE.

**Comment by marsDurden** [comment]
My bad, I didn't have gcc on my system.

**Comment by nicolas-chaulet** [comment]
Ha! Great, I was not sure how to solve that...
